[package]
name = "cargo-trust"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.4.0"